### PR TITLE
autoswitch to darkmode (macOS only)

### PR DESCRIPTION
**Pull request by Norkep**
Based on System Preferences

### CODE REVIEW

**Comment by jerry1100** [comment]
Hey @Norkep, appreciate you taking the time to submit a PR. Unfortunately, I don't think we should follow the system settings as there may be users who prefer system light mode but want to use messenger dark mode.

Related: #4

**Comment by Norkep** [comment]
Can I release my own Chrome extension? 
I'll mention your github name on the code.

**Comment by jerry1100** [comment]
Go for it, but I ask that you come up with your own icon so users don't get confused.

**Comment by Norkep** [comment]
Sure!
Thanks, 

____
Maël Jallais
maeljallais.com

**Pull request closed without merging**
